# Generated by Django 4.2 on 2024-03-09 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='billing_address_1',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='billing_address_2',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='billing_city',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='billing_state',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='billing_zip',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='shipping_address_1',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='shipping_address_2',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='shipping_city',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='shipping_state',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='shipping_zip',
        ),
        migrations.AddField(
            model_name='customer',
            name='default_billing_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_customers', to='address.address'),
        ),
        migrations.AddField(
            model_name='customer',
            name='default_shipping_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipping_customers', to='address.address'),
        ),
    ]
