version: '3.7'

services:

  mysql:
    image: mysql:latest
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: orderprocess
      MYSQL_USER: tekano
      MYSQL_PASSWORD: mypassword
      MYSQL_ROOT_PASSWORD: myverysafepassword
    

  redis:
    image: redis:latest

  django:
    container_name: django
    build:
      context: ./backend
    # command: python manage.py runserver 0.0.0.0:8001
    command: uvicorn backend.asgi:application --host 0.0.0.0 --port 8001 --workers 4 --reload
    ports:
      - 8001:8001
    volumes:
      - ./backend:/usr/src/app/
    environment:
      - SECRET_KEY=django-insecure-32+vg^n#kp_*usd78pkdr)qnoj&zzzh0=a8v)&cth%5+$n-g(a
      - DEBUG=1
      - ALLOWED_HOSTS= localhost,127.0.0.1
    depends_on:
      - redis
      - mysql
  
  react:
    container_name: react
    build:
      context: ./frontend
    # command: npm run dev
    volumes:
      - ./frontend/src:/app/src
    ports:
      - 5173:5173

  celery:
    container_name: celery
    build:
      context: ./backend
    command: celery -A backend  worker -l INFO 
    volumes:
      - ./backend:/usr/src/app/
    environment:
      - SECRET_KEY=django-insecure-32+vg^n#kp_*usd78pkdr)qnoj&zzzh0=a8v)&cth%5+$n-g(a
      - DEBUG=1
      - ALLOWED_HOSTS= localhost,127.0.0.1
    depends_on:
      - redis
      - django