FROM python:3.11.4-alpine

# prevent python from writing .pyc files to the container
ENV PYTHONDONTWRITEBYTECODE 1

# prevent python from buffering stdout and stderr
ENV PYTHONUNBUFFERED 1

RUN pip install --upgrade pip

COPY ./backend/requirements.txt .

RUN apk update && apk add --no-cache \
    mariadb-dev \
    gcc \
    musl-dev \
    && rm -rf /var/cache/apk/* 

RUN  pip install --upgrade pip
RUN pip install --upgrade setuptools
    
RUN python3 -m pip install -r requirements.txt

COPY ./backend /backend

COPY ./conf/migrations.sh /backend

WORKDIR /backend

ENTRYPOINT ["sh", "./migrations.sh"]