# Generated by Django 4.2 on 2024-03-10 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttype',
            name='action',
            field=models.CharField(choices=[('approve', 'Approve'), ('inspect', 'Inspect'), ('ship', 'Ship'), ('package', 'Package'), ('assemble', 'Assemble')], default='approve', max_length=255),
        ),
    ]
