# Generated by Django 4.2 on 2024-03-18 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='clickup_user_id',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='clickup_id',
            field=models.CharField(editable=False, max_length=255),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('urgent', 'Urgent'), ('high', 'High'), ('normal', 'Normal'), ('low', 'Low')], default='normal', max_length=255),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('in progress', 'In Progress'), ('completed', 'Completed'), ('deferred', 'Deferred'), ('pending', 'Pending'), ('packaged', 'Packaged'), ('installed', 'Installed'), ('assessment', 'Assessment')], default='pending', max_length=255),
        ),
    ]
